apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - app-argocd.yaml
  - app-of-apps.yaml
  - app-of-prerequisites.yaml
patchesStrategicMerge:
  - argocd-server-service.yaml
  - argocd-configmap.yaml
